### ISSUE TITLE
Key bindings that reference <Plug> stopped working; calling :ALE functions instead work

### ISSUE THREAD

**Issue by EdmundsEcho** [w0rp/ale#1437]
Great plugin.  I hope describing this bug helps.

## Information

**VIM version**
NVIM v0.2.2
Build type: Release
LuaJIT 2.0.5

Operating System: 
Mac OS

### :ALEInfo
_Note: I just updated my  plugins to make sure this remains relevant._

 Current Filetype: haskell
Available Linters: ['ghc-mod', 'stack-ghc-mod', 'ghc', 'hdevtools', 'hlint', 'stack-build', 'stack-ghc']
  Enabled Linters: ['stack-ghc-mod', 'hdevtools', 'hlint']
 Linter Variables:

let g:ale_haskell_hdevtools_executable = 'hdevtools'
let g:ale_haskell_hdevtools_options = '-g -Wall'
 Global Variables:

let g:ale_cache_executable_check_failures = 0
let g:ale_change_sign_column_color = 0
let g:ale_command_wrapper = ''
let g:ale_completion_delay = 100
let g:ale_completion_enabled = 0
let g:ale_completion_max_suggestions = 50
let g:ale_echo_cursor = 1
let g:ale_echo_msg_error_str = 'Error'
let g:ale_echo_msg_format = '%code: %%s'
let g:ale_echo_msg_info_str = 'Info'
let g:ale_echo_msg_warning_str = 'Warning'
let g:ale_enabled = 1
let g:ale_fix_on_save = 1
let g:ale_fixers = {'javascript': ['prettier-eslint'], 'css': ['prettier']}
let g:ale_history_enabled = 1
let g:ale_history_log_output = 1
let g:ale_keep_list_window_open = 0
let g:ale_lint_delay = 200
let g:ale_lint_on_enter = 1
let g:ale_lint_on_filetype_changed = 1
let g:ale_lint_on_save = 1
let g:ale_lint_on_text_changed = 'always'
let g:ale_lint_on_insert_leave = 0
let g:ale_linter_aliases = {}
let g:ale_linters = {'jsx': ['eslint'], 'haskell': ['hlint', 'hdevtools', 'stack-ghc-mod'], 'json': ['jsonlint', 'prettier'], 'javascript': ['eslint'], 'css': ['csslint', 'prettier']}
let g:ale_linters_explicit = 0
let g:ale_list_window_size = 10
let g:ale_list_vertical = 0
let g:ale_loclist_msg_format = '%code: %%s'
let g:ale_max_buffer_history_size = 20
let g:ale_max_signs = -1
let g:ale_maximum_file_size = 0
let g:ale_open_list = 0
let g:ale_pattern_options = {}
let g:ale_pattern_options_enabled = 0
let g:ale_set_balloons = 0
let g:ale_set_highlights = 1
let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_set_signs = 1
let g:ale_sign_column_always = 0
let g:ale_sign_error = '>>'
let g:ale_sign_info = '->'
let g:ale_sign_offset = 1000000
let g:ale_sign_style_error = '>>'
let g:ale_sign_style_warning = '->'
let g:ale_sign_warning = '->'
let g:ale_statusline_format = ['%d error(s)', '%d warning(s)', 'OK']
let g:ale_type_map = {}
let g:ale_warn_about_trailing_blank_lines = 1
let g:ale_warn_about_trailing_whitespace = 1
  Command History:

(executable check - success) stack
(executable check - success) hdevtools
(executable check - success) hlint

## What went wrong
1. NVim stopped navigating to the next error using the key bindings set in the config file. I don't know exactly when.  I run updates regularly.
1. When I changed the setting from `<Plug>(ale_next_wrap)` to `:ALENext<CR>`, the plugin behaves as expected (also relevant for `previous`, the only other key binding I use for ALE)

__The issue:__ The documentation seems to imply we can use either way to set the bindings.  When troubleshooting the issue, changing the reference syntax to the ALE functions is low in the priority list of things to try.  

## Reproducing the bug
Use the following in the config:  `<Plug>(ale_next_wrap)`
## Fix/hack?
Use the following in the config: `:ALENext<CR>`

**Comment by w0rp** [comment]
The plug mapping ought to work, so that should be fixed.

**Comment by w0rp** [comment]
They work just fine for me. I tried again with the latest commit. Here are the keybinds I use.

```vim
nmap <silent> <C-k> <Plug>(ale_previous_wrap)
nmap <silent> <C-j> <Plug>(ale_next_wrap)
```

**Comment by EdmundsEcho** [comment]
Thank you for testing it out at your end.  I just confirmed the behavior at my end on another computer (macbook instead of macpro).  The NVIM configurations are nearly identical.  

I use <space> as my leader.  This said, I just tested it using <C-k> and still do not get a response.  This is not 100% conclusive because I use <C-k> to move between tmux/vim windows and did not delete all of those related settings...

**Comment by Gidgidonihah** [comment]
I've run into this issue as well. In my debugging (take it down to only ALE installed, only 3 lines in my vimrc), I still couldn't get it to work.

I took the odd next step of remapping Ctrl+(every character) and it started working. 
This led me to figure out that this line:
```
nmap <silent> <C-m> <Plug>(ale_next_wrap)
```
Makes it so `Ctrl+j` works. WTF?!

**Comment by RyanSquared** [comment]
`ctrl-j` and `ctrl-m` are both considered to be "enter" keys (go ahead and try in your shell, `echo test<C-J>`). This is an odd behavior of old terminals that I feel Vim just decides is appropriate enough that all keybinds that map to the enter key have the same functionality.
